### ISSUE TITLE
Consider not running ``yum update`` in Dockerfile

### ISSUE THREAD

**Issue by erickpeirson** [arXiv/arxiv-base#130]
https://github.com/arXiv/arxiv-base/blob/cc9eb8f9b5e22e643c3a669420d6f9931acb1bfd/Dockerfile#L11

See https://developers.redhat.com/blog/2016/03/09/more-about-docker-images-size/

**Comment by bbarker** [comment]
Some consolation is that we are doing `yum clean` in the same RUN command

https://github.com/arXiv/arxiv-base/blob/cc9eb8f9b5e22e643c3a669420d6f9931acb1bfd/Dockerfile#L35

**Comment by erickpeirson** [comment]
True. Current thoughts:
- Do we really need ``update`` or ``update --security`` when the latest build of ``centos:7`` should be up to date? e.g. see https://github.com/CentOS/sig-cloud-instance-images/blob/9a389e11460bd809bb83c5fd4f095dbc8398d8cc/docker/Dockerfile
- I tried building the accounts app without them, and saved about 100 MB. So that was pretty nice.

**Comment by bbarker** [comment]
Good points. CC @rcplane - any thoughts? (I know you are sick today - so just flagging you for your thoughts at some point).
