### ISSUE TITLE
Use boto3 Kinesis WaiterConfig instead of Python retry when waiting for stream

### ISSUE THREAD

**Issue by erickpeirson** [arXiv/arxiv-base#144]
https://github.com/arXiv/arxiv-base/blob/0bbb1410fa99e54f9ac8e7cdb1a410d20a4475ce/arxiv/integration/kinesis/consumer/__init__.py#L270-L272

Using ``retry`` introduces an extra layer of complexity, since boto3's waiter already implements some retry logic. Using ``WaiterConfig`` like this is much simpler:

```python
                WaiterConfig=dict(
                    Delay=delay,
                    MaxAttempts=tries,
                    ExclusiveStartShardId=self.shard_id
                )
```

**Comment by bdc34** [comment]
No longer using kinesis.
