### ISSUE TITLE
Link broken: donate url in user page

### ISSUE THREAD

**Issue by lsvih** [arXiv/arxiv-base#254]
Hi there, 

Seems the problem mentioned in #228 still exists on user page.

Reproduce steps:

1. Login
2. Go to the user page `https://arxiv.org/user/`
3. The `Donate` link in the header points to `https://arxiv.org/user/info.arxiv.org/about/donate.html`, which should have been fixed by #228 .

**Comment by jweiskoff** [comment]
This has been fixed.
