### ISSUE TITLE
Bulk access via torrents?

### ISSUE THREAD

**Issue by rossmounce** [arXiv/arxiv-base#73]
I decided to test out the bulk download system [via the S3 service](https://arxiv.org/help/bulk_data_s3).

I choose to download all fulltext PDFs from 2015:
arXiv_pdf_1501_001.tar through to arXiv_pdf_1512_019.tar 

It works which is great. 

But it cost me $10.95 inc. tax
![image](https://user-images.githubusercontent.com/824120/44575401-d7549880-a783-11e8-916e-04cf838785f2.png)

Why can't libraries around the world just help torrent these highly valuable bulk files? 
Many libraries/institutions seem happy to host mirrors of things like [CPAN](http://mirrors.cpan.org/) & [CRAN](https://cran.r-project.org/mirrors.html), why not arxiv bulk files?

Academic Torrents has a tiny slice of arxiv but not enough people are seeding it :cry: 
http://academictorrents.com/collection/arxiv 

Has the arxiv team enquired about this possibility before with the world's major libraries?

**Comment by erickpeirson** [comment]
Great questions.

> But it cost me $10.95 inc. tax

The S3 pays model definitely needs to change. One of the primary use-cases that I am aware of for bulk download of PDFs is text mining. One of the things that we're working on right now is providing better access to plain text content, which we use for internal purposes but will also be far less costly to provide to external users. Take a look at https://cul-it.github.io/arxiv-fulltext/and https://github.com/cul-it/arxiv-fulltext for more info.

> Why can't libraries around the world just help torrent these highly valuable bulk files?

We've been steadily retiring our mirror sites over the years. The biggest reason is that the classic system is heavy to run even as a mirror, and requires care and feeding (human cycles that are already stretched thin). At the same time, I do think that there is a role here for libraries to help provide access. As the NG project gets further along, I expect to flesh out a fresh approach to mirrors in general.

> Has the arxiv team enquired about this possibility before with the world's major libraries?

We haven't specifically explored torrents as an option for redistribution. But it's an interesting idea! One challenge that we need to address are the possible constraints placed on us by the arXiv 1.0 license with regard to redistribution. Definitely not off the table, once we get a little further along with some of our core distribution work.

**Comment by nemobis** [comment]
Note, the dumps are also on archive.org:
https://archive.org/details/arxiv-bulk?sort=-publicdate

Any library wishing to mirror them just has to seed the respective torrents.

**Comment by rossmounce** [comment]
Thanks @nemobis I didn't actually know that archive.org has arxiv dumps.

**Comment by amacfie** [comment]
Any update on whether the license would allow torrenting?
